// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRLYmOaVqoPC2USscaujRDdCtOC11s3kU',
    appId: '1:660932784250:web:eff2c9aa21619965c74bc3',
    messagingSenderId: '660932784250',
    projectId: 'patient-55976',
    authDomain: 'patient-55976.firebaseapp.com',
    storageBucket: 'patient-55976.appspot.com',
    measurementId: 'G-Z21KTC801C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5k__WPfKAIbJ6V05RuNSdOhFf6ERQZ8U',
    appId: '1:660932784250:android:a563762da04a1889c74bc3',
    messagingSenderId: '660932784250',
    projectId: 'patient-55976',
    storageBucket: 'patient-55976.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0_C7FewVMgncz05zsYX9GnCGwv2pj7pQ',
    appId: '1:660932784250:ios:3147c9b0ffb21fd1c74bc3',
    messagingSenderId: '660932784250',
    projectId: 'patient-55976',
    storageBucket: 'patient-55976.appspot.com',
    iosBundleId: 'com.example.swastha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0_C7FewVMgncz05zsYX9GnCGwv2pj7pQ',
    appId: '1:660932784250:ios:3147c9b0ffb21fd1c74bc3',
    messagingSenderId: '660932784250',
    projectId: 'patient-55976',
    storageBucket: 'patient-55976.appspot.com',
    iosBundleId: 'com.example.swastha',
  );
}
